<?php

require __DIR__.'/../vendor/autoload.php';
$app = require_once __DIR__.'/../bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Afiliado;
use App\Models\Estado;
use App\Models\HistorialEstado;
use Illuminate\Support\Facades\DB;

$nombres = [
'CHRISTOPHER ALEXANDER PEÑA MINYETY', 'MARITZA PIÑA FAMILIA', 'EMILIA MISAREL VELEZ BATISTA', 
'LESLY TERRERO CARRASCO', 'RONNY HERRERA FELIZ', 'ANGEL MIGUEL MENDEZ PEREZ', 
'GABRIEL CARELA FERNANDEZ', 'HECTOR DAVID GUERRA CORDERO', 'FENNI MANUEL MELENDEZ ALCANTARA', 
'JUANSHY LOGAN FAMILIA LOPEZ', 'ANGEL GLEISON FERRERAS SANCHEZ', 'LEONARDO ALFREDO PEROZO FREITES', 
'YISMERLIN CASTILLO SANTANA', 'HEILIN MABEL VASQUEZ', 'NAHIOMY ANGUSTIA', 'FRANYELI SOLANO GUZMAN', 
'NIULKA TEXENERIS CASTILLO PEREZ', 'RAUL STIVEN MANUEL SANCHEZ', 'FRANCIEL ORTIZ GUZMAN', 
'MAIROBI SANTANA', 'EMELY NAYALY MARTINEZ LOPEZ', 'YADIEL SATURRIA', 'SANTIAGO DAVID MARTE', 
'JUAN MANUEL DE LA CRUZ', 'SANTA BAYO ETIMO', 'ERICK ELIZANDER MEDINA MARTE', 
'JEFERSON HUMBERT BUCA ANGULO', 'MARINO QUEZADA PEREZ', 'ANYI VANESSA NUÑEZ', 'DARY ACOSTA LA PAZ', 
'ELMANUEL DE LA ROSA MAÑON', 'YOJEURIS VILLANUEVA BONE', 'LUBLI SHANTHAL PEGUERO REYES', 
'ELISEO CALIZAN CALDERON', 'FRANCIS ILANDYS ROSARIO DE LA CRUZ', 'LUIS ANGEL OTAÑEZ CASTILLO', 
'INDIANA YESMEL MEDRANO VOLQUEZ', 'FREIDENIS PEREZ PEREZ', 'RAYNER ALEXANDER DIAZ RIVERA', 
'ALAN MANUEL SANTANA TAVERAS', 'ANGEL DANIEL ABREU GARCIA', 'PEDRO ANTONIO RAMIREZ GALAN', 
'Veronica Castro De La Cruz', 'YAERNI IBELISE MOSQUEA', 'JEISON ALCANTARA MOQUETE', 
'SANDRA VENTURA SANTOS', 'SCARLLETT GARCIA MATEO', 'DARLENY MARTINEZ DUARTE', 
'LEIDY DAHIANA ALCANTARA DE LOS SANTOS', 'MARIA ALEXANDRA MALDONADO ARIAS', 
'ALEXA MISEL MANZUETA TAPIA', 'ANGEL JOVANNY CARPIO SOLER', 'RICKI GUZMAN FRANCO', 
'EDUARDO RODRIGUEZ PEÑA', 'ELVIS ALEXANDER GERONIMO JIMENEZ', 'JOHAN DAVID DE LEON NOBOA', 
'GABRIEL JIMENEZ', 'BRENDA MICHELLE VASQUEZ ALCALA', 'ESCARLETT DILALNI MONTERO PEREZ', 
'LAURA AMELIA REYES HERNANDEZ', 'JEAN LUIS DE JESUS NUÑEZ CRUZ', 'JUNIOR ALEXANDER SURIEL POLANCO', 
'JONATHAN FERNANDEZ TORRES', 'SEBASTIAN FERNANDEZ', 'GABRIELA ADON YAN', 'LOURDE ALICIA DE JESUS CUEVAS', 
'DANIELA DE LA CRUZ TORRES', 'MISAEL GOMEZ MICHEL', 'CANDY OLISBEL MONTERO ENCARNACION', 
'FREYDILENI RODRIGUEZ RODRIGUEZ', 'SALI SERRANO SUERO', 'ESMEURI MANUEL SANTIAGO GARCIA', 
'CARLOS ANTONIO SABALA MARTINEZ', 'ANYELO CRISOSTOMO VERAS', 'STARLING DE JESUS BATISTA PEÑA', 
'VIRGINIA MONTERO', 'BLADIMIR RABEL PIERRE LOUIS', 'ARINSON JOSE PLACENCIO GONZALEZ', 
'WANER FRANCO LARA', 'JORGE LUIS ARIAS PIMENTEL', 'WANER EUDIN CUELLO BRITO', 
'ANA CRISTINA ARIAS MENDEZ', 'NIXON JIMENEZ TRINIDAD', 'ISMAEL BENJAMIN PEGUERO', 
'MARKELLY SANTOS CALCAÑO', 'ENRIQUE LIRANZO UREÑA', 'DIONICIO CARRERAS DE LOS SANTOS', 
'ARISTIDES SANTANA CASTRO', 'MAYCKEL LUIS ROMERO FELIZ', 'CHRISTIAN ALEXANDER CORDERO GARCIA', 
'ALEJANDRO JOSE TINTORI PARRA', 'DANNY ARAGONES MARTE', 'ELIEZER ANTONIO ROSARIO PAULA', 
'ANGEL MASSIEL MONTERO MONTERO', 'CARLOS JOSE NIVAR', 'CARLOS RAFAEL CARMONA', 
'CRUZ JOSE GUZMAN MARTINEZ', 'EDWARD AYBAR PEREZ', 'FRANKLIN STIBEN NICASIO', 
'GRISELY ORTIZ ARIAS', 'HANSEL ISIDRO GUERRERO MOREL', 'HARLIN MANUEL SOTO LARA', 
'JHONAIRIS FUENTES ROSSIS', 'JONATHAN ALEJANDRO SUAREZ DUME', 'JORGE PEREZ GUERRERO', 
'JUNIOR NUÑEZ LANTIGUA', 'KEISY NATASHA ARIAS HERRERA', 'RAHICHE JEANCARLOS ZOQUIER', 
'SANTOS RAYNIEL LARA', 'YEIMI YOKAURY SANTANA', 'YOELY SANTANA CASTRO', 'YONAIKEL JOSE PIMENTEL SUAZO', 
'YONKARY ALTAGRACIA SANTANA MEJIA', 'YEIMI MANUELA CASTILLO TEJEDA', 'ISRAEL RAMIREZ SEVERINO', 
'SARAH RODRIGUEZ MARTINEZ', 'YINET MENDEZ FIGUEREO', 'CARLOS DANIEL REYES DE LOS SANTOS', 
'RUTH DELIZ GENAO ACEVEDO', 'JOHN MATTH MARTE DAVID', 'ENMANUEL AGRAMONTE ESTEVEZ', 
'JOSE DAVID GERMAN MOTA', 'JOSE NOEL HINOJOSA VICIOSO', 'JUAN CARLOS CRISTOBAL DE LA CRUZ', 
'SMIL MANZUETA PEREZ', 'YEFRY ACOSTA MORILLO', 'EMELI NICOL BELLO VIZCAINO', 
'ENMANUEL ROSARIO CARREÑO', 'MISAEL MATEO DE LA ROSA', 'WILLY BOTIER ENCARNACION', 
'FLORMELYS RODRIGUEZ GOMEZ', 'ERICSON DE LA CRUZ JIMENEZ', 'BRAHIAN ANTONIO ALMONTE RODRIGUEZ', 
'JEAN DANIEL VASQUEZ RODRIGUEZ', 'DEANGELO GENAO ESTEVEZ', 'ALEXANDER BATISTA JIMENEZ', 
'JORGE DANIEL HENRRY DE LA CRUZ', 'YAXEL ALBERTO VALENTIN ACOSTA', 'RUDDY JAEL GUZMAN', 
'ELIAN ANTONIO PERALTA MARTINEZ', 'ELIEZER DE PAULA DE LA CRUZ', 'VICTOR JESUS LOPEZ DIAZ', 
'JOHAN GENAO PEREZ', 'JOHAN MANUEL MARIÑEZ LINARES', 'RAQUEL ALMONTE JAQUEZ', 
'KELVYN JOSMAR CAMBERO', 'MAIKEL MANUEL LIRANZO LORENZO', 'JEAN PAUL ROBERDEAU PIMENTEL', 
'BRITHANY MICHELLE MONTERO MATEO', 'FRANCARI MANUELA MEJIA ABAD', 'WALDO MEDINA RAMIREZ', 
'JOSIANNY ENCARNACION DE LA CRUZ', 'MELANIE ARIANNA TRONCOSO NOVA', 'ELIANNI QUEVEDO VALDEZ', 
'ANTONELLA CRISTIN ESCOTTO TORRES', 'ARTURO NICOLAS VELOZ VICTORIA', 'DIEGO PAUL GERMAN', 
'EIMY LISMEL REYNOSO SANTOS', 'AUDREY MELINA ENCARNACION ALCANTARA', 'ALAM RAFAEL DE LOS SANTOS MARTINEZ', 
'CRISTAL MARIA MANZANILLO CESAR', 'JOEL DANIEL GARCIA MERCEDES', 'JEAN DIERY GARCIA GUZMAN', 
'MARIA ANGEL FELIX SANTIAGO', 'ROSIBEL DE LOS SANTOS MONTERO', 'PAMELA BELTRE DISLA', 
'FRAINEL MANUEL SILFA PANIAGUA', 'ANGEL YANDEL PINEDA JAQUEZ', 'EDWIN DE LEON', 
'YENDER JAVIER DIAZ RODRIGUEZ', 'MARIANELA MAÑANA ROBLES', 'ALBERT SUERO FAJARDO', 
'JADIEL NAZARE MELENDEZ RAMIREZ', 'ADAN JOSE MORILLO DE OLEO', 'ALFRANI SANTANA PEÑA', 
'JOSE RAFAEL POLANCO PEÑA', 'JUAN FERNANDO ZULUAGA MENDEZ', 'CESAR GERARDO SERRANO DE', 
'ERICK LUIS MONTILLA RAZON', 'KEFRY PAULINO COMAS', 'EMELY DE LA CRUZ ROCHE', 
'MELKI ELIAN RODRIGUEZ CERDA', 'ABIGAIL GUERRERO TINEO', 'MOISES JAVIER OGANDO', 
'ADIEL NOMAR GOMEZ GUZMAN', 'ALONDRA DIAZ ENCARNACION', 'ANDRES MICHAEL FERRER GURIDY', 
'JOSMAIRY BRITO RODRIGUEZ', 'JHAN CARLOS VELEZ MATOS', 'LAIONEL FLAMEL ROSA MATA', 
'PAVEL ALEJANDRO LANTIGUA MELO', 'BRENNY AYBAR VICTORIANO', 'MARIA ALEJANDRA LIRIANO REYNOSO', 
'YAHAIRA HERNANDEZ CORREA', 'YEUDDI REYES GALVAN', 'DARLYN JOSE MENDOZA ESPINOSA', 
'HILARY BURGOS GRULLON', 'WANDY DE LEON MOTA', 'JESUS ENMANUEL MERCEDES ABREU', 
'MASSIEL MARIE RAMIREZ', 'JOSE ARMANDO ESPINAL RAMIREZ', 'WILFRY JIMENEZ RODRIGUEZ', 
'ANGELICA MARIA FERRERAS PEÑA', 'ELIANNY LEBRON ESPINAL', 'BRAYAN ISMAEL LUIS VALDEZ'
];

$completado_id = Estado::where('nombre', 'Completado')->value('id') ?? 9;

$stats = [
    'nombres_procesados' => count($nombres),
    'afiliados_encontrados' => 0,
    'actualizados' => 0,
    'ya_completados' => 0,
    'no_encontrados' => 0
];

try {
    DB::beginTransaction();

    foreach ($nombres as $nombre) {
        $nombre_clean = trim($nombre);
        $afiliados = Afiliado::where('nombre_completo', 'LIKE', $nombre_clean)->get();

        if ($afiliados->isEmpty()) {
            $stats['no_encontrados']++;
            continue;
        }

        foreach ($afiliados as $afiliado) {
            $stats['afiliados_encontrados']++;

            if ($afiliado->estado_id == $completado_id) {
                $stats['ya_completados']++;
                continue;
            }

            $oldEstado = $afiliado->estado_id;
            $afiliado->estado_id = $completado_id;
            $afiliado->save();

            HistorialEstado::create([
                'afiliado_id' => $afiliado->id,
                'estado_anterior_id' => $oldEstado,
                'estado_nuevo_id' => $completado_id,
                'user_id' => 1,
                'observacion' => 'Actualización masiva por Nombre (Lote 3): Marcado como completado por solicitud de usuario.'
            ]);

            $stats['actualizados']++;
        }
    }

    DB::commit();

    echo "Reporte de Operación Lote 3 (Nombres):\n";
    echo "--------------------------\n";
    echo "Nombres en el listado: {$stats['nombres_procesados']}\n";
    echo "Afiliados encontrados: {$stats['afiliados_encontrados']}\n";
    echo "Ya estaban completados: {$stats['ya_completados']}\n";
    echo "Actualizados ahora: {$stats['actualizados']}\n";
    echo "Nombres no localizados: {$stats['no_encontrados']}\n";

} catch (\Exception $e) {
    DB::rollBack();
    echo "Error: " . $e->getMessage() . "\n";
}
